# Generated by Django 6.0 on 2026-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20)),
                ('league_type', models.CharField(default='Niższe ligi', editable=False, max_length=50)),
                ('province', models.CharField(choices=[('dolnośląskie', 'Dolnośląskie'), ('kujawsko-pomorskie', 'Kujawsko-Pomorskie'), ('lubelskie', 'Lubelskie'), ('wielkopolskie', 'Wielkopolskie')], max_length=100)),
                ('competition_class', models.CharField(choices=[('Czwarta liga', 'Czwarta liga'), ('Piąta liga', 'Piąta liga'), ('Klasa okręgowa', 'Klasa okręgowa'), ('Klasa A', 'Klasa A'), ('Klasa B', 'Klasa B'), ('Klasa C', 'Klasa C')], max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
