# Generated by Django 6.0 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
