# Generated by Django 6.0 on 2026-05-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_class', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('team', models.CharField(max_length=50)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('win_count', models.PositiveIntegerField(default=0)),
                ('draw_count', models.PositiveIntegerField(default=0)),
                ('loose_count', models.PositiveIntegerField(default=0)),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('goals_balance', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Leagues.league')),
            ],
        ),
    ]
