# Generated by Django 6.0 on 2026-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Transfery', 'Transfery'), ('Mecze', 'Mecze'), ('Puchary', 'Puchary')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
